force-app/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DeliveryInstallationStatus__c</fullName>
        <label>Delivery/Installation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Yet to begin</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/classes/ProjectRESTService.cls
@RestResource(UrlMapping='/project')
global class ProjectRESTService {

    @HttpPost
    global static String postProjectData(String ProjectRef, String ProjectName, String OpportunityId, Date StartDate,
            Date EndDate, Double Amount, String Status) {
        RestRequest req = RestContext.request;

        Savepoint sp = Database.setSavepoint(); //Savepoint before making DML statements
        try {
            Project__c projectRecord = new Project__c();
            projectRecord.Name = ProjectName;
            projectRecord.ProjectRef__c = ProjectRef;
            projectRecord.Opportunity__c = OpportunityId;
            projectRecord.Start_Date__c = StartDate;
            projectRecord.End_Date__c = EndDate;
            projectRecord.Billable_Amount__c = Amount;
            projectRecord.Status__c = Status;


            upsert projectRecord ProjectRef__c;

            Opportunity oppRelated = [SELECT Id FROM Opportunity WHERE Id = :OpportunityId];
            oppRelated.DeliveryInstallationStatus__c = 'In progress';
            update oppRelated;

            return 'OK';
        }
        catch (Exception ex) {
            System.debug('>> Exception with DML statements:' + ex.getMessage());
            Database.rollback(sp);
            return 'Error with the REST service';
        }
    }
}