force-app/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/objects/ServiceCredentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Username and password credentials for external services</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for the external service</description>
        <label>Password</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>User for the external service</description>
        <label>Username</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ServiceCredentials</label>
</CustomObject>

force-app/classes/BillingCalloutService.cls
public class BillingCalloutService {

    public static BillingServiceProxy.project proxyProject;

    public static void callBillingService(Project__c newProjectRec) {

        //Get credentials for callout
        ServiceCredentials__c credentials = [SELECT Id, Username__c, Password__c FROM ServiceCredentials__c][0];

        //Fill information of project
        proxyProject = new BillingServiceProxy.project();
        proxyProject.username = credentials.Username__c;
        proxyProject.password = credentials.Password__c;
        proxyProject.projectid = newProjectRec.ProjectRef__c;
        proxyProject.billAmount = newProjectRec.Billable_Amount__c;

        //Callout
        calloutBillingService(newProjectRec.Id);
    }

    @Future(Callout=true)
    private static void calloutBillingService(Id idProj) {
        Project__c newProjectRec = [SELECT Id, Status__c FROM Project__c WHERE Id =: idProj];
        BillingServiceProxy.InvoicesPortSoap11 invoice = new BillingServiceProxy.InvoicesPortSoap11();
        String responseBilling = invoice.billProject(proxyProject);

        List<Project__c> projToUpdate = new List<Project__c>();
        if(responseBilling == 'OK') {
            newProjectRec.Status__c = 'Billed';
            projToUpdate.add(newProjectRec);
        }
        update projToUpdate;
    }
}